apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-top-level
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevin-kho/test-argocd-finalizers
    targetRevision: HEAD
    path: app-of-apps
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
